name: Build kobo-btpt PR32
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: pgaskin/kobo-btpt
          ref: update-nh
          submodules: recursive
      - name: Build
        run: make clean all koboroot
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: kobo-btpt-pr32
          path: KoboRoot.tgz
